name: GitHub Actions Demo
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: golang:1.19
    steps:
      - uses: actions/checkout@v3
      - run: go install github.com/bufbuild/buf/cmd/buf@v1.11.0